/* ========================================
   CyneMora — Gemini 3 Pro Image Provider
   Google Gemini API image generation
   Server-side only
   ======================================== */

import { GoogleGenAI } from "@google/genai";
import {
  ImageProvider,
  ImageProviderConfig,
  ImageInstruction,
  ImageOperation,
  ImageResult,
} from "./provider";

const GEMINI_IMAGE_CONFIG: ImageProviderConfig = {
  name: "Gemini 3 Pro Image",
  model: "gemini-2.0-flash-preview-image-generation",
  maxImages: 4,
  supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
  supportedStyles: [
    "photorealistic", "illustration", "anime", "watercolor",
    "oil-painting", "sketch", "3d-render", "pixel-art",
    "cinematic", "concept-art"
  ],
  supportsNegativePrompt: true,
  supportsReferenceImages: true,
  costMultiplier: 0.8,
  strengths: [
    "concept-creation", "storyboarding", "creative-ideation",
    "visual-storytelling", "design-exploration", "multimodal"
  ],
};

/**
 * Gemini image provider implementation.
 * Uses the Gemini API's native image generation capability
 * (generateContent with image output modality).
 *
 * Strengths:
 * - Concept creation & storyboarding
 * - Creative ideation & visual storytelling
 * - Design exploration
 * - Multimodal generation
 */
export class GeminiImageProvider implements ImageProvider {
  readonly name = "gemini-image";
  readonly config = GEMINI_IMAGE_CONFIG;
  private client: GoogleGenAI;

  /** In-memory store for completed sync operations */
  private completedOps = new Map<string, ImageResult>();

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error(
        "GEMINI_API_KEY is not configured. Gemini Image provider cannot initialize."
      );
    }
    this.client = new GoogleGenAI({ apiKey });
  }

  async isAvailable(): Promise<boolean> {
    try {
      return !!process.env.GEMINI_API_KEY;
    } catch {
      return false;
    }
  }

  async generateImages(instruction: ImageInstruction): Promise<ImageOperation> {
    const operationId = `gemini-img-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    try {
      const numberOfImages = Math.min(instruction.numberOfImages || 1, this.config.maxImages);

      // Build style context into the prompt
      let enhancedPrompt = instruction.prompt;
      if (instruction.style) {
        enhancedPrompt = `${instruction.prompt}. Style: ${instruction.style}`;
      }
      if (instruction.negativePrompt) {
        enhancedPrompt += `. Avoid: ${instruction.negativePrompt}`;
      }

      // Generate images (Gemini does this synchronously per call)
      const imageUrls: string[] = [];

      for (let i = 0; i < numberOfImages; i++) {
        const response = await this.client.models.generateContent({
          model: GEMINI_IMAGE_CONFIG.model,
          contents: enhancedPrompt,
          config: {
            responseModalities: ["TEXT", "IMAGE"],
          },
        });

        // Extract generated image data from the response
        if (response.candidates && response.candidates.length > 0) {
          const candidate = response.candidates[0];
          if (candidate.content?.parts) {
            for (const part of candidate.content.parts) {
              if (part.inlineData?.mimeType?.startsWith("image/")) {
                // Convert base64 data to a data URL for now;
                // the status route will persist these to Firebase Storage
                const dataUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                imageUrls.push(dataUrl);
              }
            }
          }
        }
      }

      if (imageUrls.length === 0) {
        return {
          id: operationId,
          provider: this.name,
          status: "failed",
          error: "No images were generated by Gemini",
        };
      }

      // Store result for later retrieval
      const result: ImageResult = {
        imageUrls,
        width: instruction.width || 1024,
        height: instruction.height || 1024,
        provider: this.name,
        prompt: instruction.prompt,
        metadata: {
          model: GEMINI_IMAGE_CONFIG.model,
          style: instruction.style,
        },
      };
      this.completedOps.set(operationId, result);

      return {
        id: operationId,
        provider: this.name,
        status: "completed",
        progress: 100,
        imageUrls,
      };
    } catch (error) {
      console.error("[GeminiImageProvider] Generation failed:", error);
      return {
        id: operationId,
        provider: this.name,
        status: "failed",
        error: (error as Error).message,
      };
    }
  }

  async checkStatus(operationId: string): Promise<ImageOperation> {
    const result = this.completedOps.get(operationId);
    if (result) {
      return {
        id: operationId,
        provider: this.name,
        status: "completed",
        progress: 100,
        imageUrls: result.imageUrls,
      };
    }
    return {
      id: operationId,
      provider: this.name,
      status: "failed",
      error: "Operation not found",
    };
  }

  async getResult(operationId: string): Promise<ImageResult> {
    const result = this.completedOps.get(operationId);
    if (!result) {
      throw new Error(`Operation ${operationId} not found or not completed`);
    }
    return result;
  }

  async cancelGeneration(_operationId: string): Promise<void> {
    // Gemini image generation is synchronous — nothing to cancel
  }
}

// Singleton
let geminiImageInstance: GeminiImageProvider | null = null;

export function getGeminiImageProvider(): GeminiImageProvider {
  if (!geminiImageInstance) {
    geminiImageInstance = new GeminiImageProvider();
  }
  return geminiImageInstance;
}
