/* ========================================
   CyneMora — OpenAI Image Provider
   OpenAI DALL-E image generation
   Server-side only
   ======================================== */

import OpenAI from "openai";
import {
  ImageProvider,
  ImageProviderConfig,
  ImageInstruction,
  ImageOperation,
  ImageResult,
} from "./provider";

const OPENAI_IMAGE_CONFIG: ImageProviderConfig = {
  name: "GPT Image 2",
  model: "dall-e-2",
  maxImages: 4,
  supportedAspectRatios: ["1:1"], // dall-e-2 only supports 1:1, 1024x1024, 512x512, 256x256
  supportedStyles: [
    "photorealistic", "illustration", "anime", "watercolor",
    "oil-painting", "sketch", "3d-render", "pixel-art",
    "cinematic", "concept-art"
  ],
  supportsNegativePrompt: false, // DALL-E 2/3 don't support negative prompts natively via API
  supportsReferenceImages: false,
  costMultiplier: 1.0,
  strengths: [
    "concept-creation", "general-purpose", "stylized-art"
  ],
};

/**
 * OpenAI image provider implementation.
 * Uses OpenAI's DALL-E model.
 */
export class OpenAIImageProvider implements ImageProvider {
  readonly name = "openai-image";
  readonly config = OPENAI_IMAGE_CONFIG;
  private client: OpenAI;

  /** In-memory store for completed sync operations */
  private completedOps = new Map<string, ImageResult>();

  constructor() {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error(
        "OPENAI_API_KEY is not configured. OpenAI Image provider cannot initialize."
      );
    }
    this.client = new OpenAI({ apiKey });
  }

  async isAvailable(): Promise<boolean> {
    try {
      return !!process.env.OPENAI_API_KEY;
    } catch {
      return false;
    }
  }

  async generateImages(instruction: ImageInstruction): Promise<ImageOperation> {
    const operationId = `openai-img-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    try {
      const numberOfImages = Math.min(instruction.numberOfImages || 1, this.config.maxImages);

      // Build style context into the prompt
      let enhancedPrompt = instruction.prompt;
      if (instruction.style) {
        enhancedPrompt = `${instruction.prompt}. Style: ${instruction.style}`;
      }
      if (instruction.negativePrompt) {
        // DALL-E doesn't have a negative prompt field, so we just append it
        enhancedPrompt += `. Do NOT include: ${instruction.negativePrompt}`;
      }

      const response = await this.client.images.generate({
        model: this.config.model,
        prompt: enhancedPrompt.substring(0, 1000), // DALL-E 2 prompt limit is 1000 chars
        n: numberOfImages,
        size: "1024x1024",
        response_format: "b64_json",
      });

      const imageUrls: string[] = [];
      if (response.data && response.data.length > 0) {
        for (const genImg of response.data) {
          if (genImg.b64_json) {
            const dataUrl = `data:image/png;base64,${genImg.b64_json}`;
            imageUrls.push(dataUrl);
          }
        }
      }

      if (imageUrls.length === 0) {
        return {
          id: operationId,
          provider: this.name,
          status: "failed",
          error: "No images were generated by OpenAI",
        };
      }

      // Store result for later retrieval
      const result: ImageResult = {
        imageUrls,
        width: 1024,
        height: 1024,
        provider: this.name,
        prompt: instruction.prompt,
        metadata: {
          model: this.config.model,
          style: instruction.style,
        },
      };
      this.completedOps.set(operationId, result);

      return {
        id: operationId,
        provider: this.name,
        status: "completed",
        progress: 100,
        imageUrls,
      };
    } catch (error) {
      console.error("[OpenAIImageProvider] Generation failed:", error);
      return {
        id: operationId,
        provider: this.name,
        status: "failed",
        error: (error as Error).message,
      };
    }
  }

  async checkStatus(operationId: string): Promise<ImageOperation> {
    const result = this.completedOps.get(operationId);
    if (result) {
      return {
        id: operationId,
        provider: this.name,
        status: "completed",
        progress: 100,
        imageUrls: result.imageUrls,
      };
    }
    return {
      id: operationId,
      provider: this.name,
      status: "failed",
      error: "Operation not found",
    };
  }

  async getResult(operationId: string): Promise<ImageResult> {
    const result = this.completedOps.get(operationId);
    if (!result) {
      throw new Error(`Operation ${operationId} not found or not completed`);
    }
    return result;
  }

  async cancelGeneration(_operationId: string): Promise<void> {
    // OpenAI image generation is synchronous — nothing to cancel
  }
}

// Singleton
let openaiImageInstance: OpenAIImageProvider | null = null;

export function getOpenAIImageProvider(): OpenAIImageProvider {
  if (!openaiImageInstance) {
    openaiImageInstance = new OpenAIImageProvider();
  }
  return openaiImageInstance;
}
